footer
AlexandraKrosnik/team-proj pull request #1
Opened 2021-12-02 06:59 UTC by AlexandraKrosnik

Тут поки немає svg. Як запушать спрайт одразу додам

2021-12-02 16:57 UTC, serpentinna commented on src/sass/base/_colors.scss
>  $button-hover-color-red: #c7133e;
ось якраз з цим кольором у мене і було питання, цей колір лише раз на весь макет знадується, мені здається це може бути помилка.

2021-12-02 16:57 UTC, serpentinna commented on src/sass/base/_colors.scss
>  $button-hover-color-lite: #ecebeb;
і з цим кольором теж. мені чомусь здається, що білий має змінюватись на червоний, а не на такий сірий. а червоний відповідно на білий, взаємозаміщатись типу.

2021-12-02 16:57 UTC, serpentinna commented on src/sass/base/_common.scss
>  }
давай може ще додамо для імеджів налаштування, display: block, height: auto, max-width: 100%?

2021-12-02 16:57 UTC, serpentinna commented on src/sass/layout/_footer.scss
> +    align-items: end;
тут треба додати flex, щоб було flex-end. наче ж так?

2021-12-02 16:57 UTC, serpentinna commented on src/sass/base/_colors.scss
> +$network-color: #fea5bb;
і цей колір теж один на всю сторінку, я думала його не виділяти окремо, може це тож помилка в дизайні.

2021-12-02 17:09 UTC, AlexandraKrosnik commented on src/sass/base/_colors.scss
>  $button-hover-color-red: #c7133e;
Мене Катя змушувала всі кольори робити змінними(
Можна у інших запитати, я не думаю що це помилка

2021-12-02 17:10 UTC, AlexandraKrosnik commented on src/sass/base/_colors.scss
>  $button-hover-color-lite: #ecebeb;
Там по макету такий колір. Думаєш варто запитати в Каті?

2021-12-02 17:10 UTC, AlexandraKrosnik commented on src/sass/base/_common.scss
>  }
Да, згодна, додам в мейн одразу

2021-12-02 17:11 UTC, AlexandraKrosnik commented on src/sass/layout/_footer.scss
> +    align-items: end;
Я гуглила, там є flex-end і є просто end, наче різниці великої немає

2021-12-02 17:12 UTC, AlexandraKrosnik commented on src/sass/base/_colors.scss
> +$network-color: #fea5bb;
В нас в минулому макеті теж були кольори які тільки раз зустрічались, наприклад ховер кнопки в герої. Чесно, не знаю

2021-12-02 17:15 UTC, serpentinna commented on src/sass/layout/_footer.scss
> +    align-items: end;
поняла, то я просто не знала) думала що випадково не додала)

2021-12-02 17:17 UTC, serpentinna commented on src/sass/base/_colors.scss
> +$network-color: #fea5bb;
от і я не знаю... точно знаю, що в дизайні не прийнято багато кольорів використовувати...я навіть не помітила що ховер кнопки в герої іншого кольору....) давай може це на дзвінку з усіма обговоримо? чи з Катьою одразу?

2021-12-02 17:17 UTC, serpentinna commented on src/sass/base/_colors.scss
>  $button-hover-color-lite: #ecebeb;
білн, не знаю...(

2021-12-03 09:19 UTC, Helarioss requested changes

2021-12-03 09:19 UTC, Helarioss commented on src/sass/layout/_footer.scss
> +    height: 44px;
На мобилке размер иконок 32px, а на таблетке и декстопе 34px. Добавь ещё `overflow: hidden`, чтобы svg не вылезала за ссылку

2021-12-03 10:20 UTC, Romandionus commented
class="footer__contact" лучше добавить font-size: 4vw с медиа правелом меньше 260 пикселей, чтобы был не перенос номера телефона, а динамически шрифт менялся

2021-12-03 10:44 UTC, Romandionus requested changes
class="footer__contact" лучше добавить font-size: 4vw с медиа правелом меньше 260 пикселей, чтобы был не перенос номера телефона, а динамически шрифт менялся

2021-12-03 19:57 UTC, merged