Начал advanteges
AlexandraKrosnik/team-proj pull request #6
Opened 2021-12-02 17:02 UTC by jokerav

2021-12-02 17:07 UTC, AlexandraKrosnik requested changes

2021-12-02 17:07 UTC, AlexandraKrosnik commented on src/partials/advantages.html
> +<section class="advanteges container">
Тут замість container має бути section. А container, це окремий дів

2021-12-02 17:07 UTC, AlexandraKrosnik commented on src/partials/advantages.html
> +        <li class="advanteges-item">
advanteges__item

2021-12-02 17:07 UTC, AlexandraKrosnik commented on src/sass/layout/_advantages.scss
> +  background-color: var($background-light-pink-color);
В тебе це працює? Бо в мене чомусь ні. Краще background-color: $background-light-pink-color;

2021-12-03 10:49 UTC, Romandionus requested changes
![image](https://user-images.githubusercontent.com/49881388/144590212-88ad064b-a2f6-49ab-8bb0-231756b9b646.png)

для того чтобы маржин заработал, надо задать дисплей блок
![image](https://user-images.githubusercontent.com/49881388/144590340-69031ae8-9c6a-4713-9077-b3ae611385ec.png)

2021-12-04 11:46 UTC, AlexandraKrosnik approved these changes

2021-12-04 11:50 UTC, Romandionus approved these changes
теперь ок

2021-12-04 11:51 UTC, merged