Feature/products
AlexandraKrosnik/team-proj pull request #7
Opened 2021-12-02 17:10 UTC by Romandionus

добавил html разметку и часть сss

2021-12-02 17:27 UTC, AlexandraKrosnik requested changes

2021-12-02 17:27 UTC, AlexandraKrosnik commented on src/sass/base/_common.scss
> +  // padding: 0 15px;
Це ти видалив padding?

2021-12-02 17:27 UTC, AlexandraKrosnik commented on src/sass/layout/_products.scss
> +  margin-bottom: 130px;
А чому 130px, по макету наче 20px?

2021-12-02 22:47 UTC, Romandionus commented
залил комит с точками и картинкой поверх карточек

2021-12-03 00:18 UTC, serpentinna approved these changes

2021-12-03 08:10 UTC, AlexandraKrosnik requested changes

2021-12-03 08:10 UTC, AlexandraKrosnik commented on src/sass/layout/_products.scss
> +    }
@media screen and (max-width: 290px) {
      transform: translate(0, -41%);
    }
Можна всім бефор дати таке медія правило і воно на менших розмірах ломатись не так сильно буде

2021-12-03 08:10 UTC, AlexandraKrosnik commented on src/partials/products.html
> +                <span></span>
Краще спану дати клас, наприклад products__points чи products__dot і стилі писати для класу. Бо якщо десь на сайті буде спан ще один, щоб ці стилі до нього не підключились

2021-12-03 08:10 UTC, AlexandraKrosnik commented on src/sass/layout/_products.scss
> +  cursor: pointer;
width: 40px;
  height: 40px;
  display: flex;
  align-items: center;
  justify-content: center;
  margin: 0 auto;
Краще замість падінгів такий варіант, Катерина через падінги вертала мені дз

2021-12-03 08:10 UTC, AlexandraKrosnik commented on src/sass/layout/_products.scss
> +}
top: 42%;
  left: 42%;
 transform: translate(-50%, -50%);
  @media screen and (max-width: 228px) {
    top: 34%;
    left: 40%;    
  }

  @media screen and (min-width: 229px) and (max-width: 270px) {
    top: 39%;   
  }

Спробуй тут так, бо мені здається transform: translate(-200%, -200%); це виглядає дуже страшно

2021-12-03 08:10 UTC, AlexandraKrosnik commented on src/sass/layout/_products.scss
> +}
Спробуй додати тут якесь медіа правило, щоб на маленьких розмірах шрифт зменшувався, і текст не вилазив за межі. Денис нам наче показував як це можна зробити через відносні величини, або просто font-size: 19px; наприклад.

2021-12-03 08:10 UTC, AlexandraKrosnik commented on src/sass/layout/_products.scss
> +}
Там де заголовок milkshakes, воно теж трішки вилазить

2021-12-03 09:12 UTC, Romandionus commented on src/sass/base/_common.scss
> +  // padding: 0 15px;
это решил раскомментировав у себя

2021-12-03 09:12 UTC, Romandionus commented on src/sass/layout/_products.scss
> +  margin-bottom: 130px;
обсуждали с тобой по макету таки 130

2021-12-03 10:06 UTC, Romandionus commented on src/sass/layout/_products.scss
> +}
задал vw + flex карточкам

2021-12-03 10:07 UTC, Romandionus commented on src/sass/layout/_products.scss
> +}
исправил как ты рекомендовало стало лучше еще добавил display none до 235 пикселей

2021-12-03 10:07 UTC, Romandionus commented on src/sass/layout/_products.scss
> +  cursor: pointer;
поправил

2021-12-03 10:07 UTC, Romandionus commented on src/partials/products.html
> +                <span></span>
products__dot мне больше понравился

2021-12-03 10:08 UTC, Romandionus commented on src/sass/layout/_products.scss
> +    }
действительно помогло

2021-12-03 19:53 UTC, AlexandraKrosnik approved these changes

2021-12-03 19:54 UTC, merged